In [2]:
import pandas as pd

voting_data = pd.read_csv("Virginia_Voting_Data.csv")
election_results = pd.read_csv("elections_results.csv")

In [3]:
voting_data.head()

,Year,Total Registered,Percentage Change from Previous Year,Total Voting,Turnout (% Voting of Total Registered),Voting Absentee (Included in Total Voting)
0,2019.0,5628035.0,-0.0100,2383646.0,0.4240,144360.0
1,2018.0,5666962.0,0.0331,3374382.0,0.5950,337315.0
2,2017.0,5489530.0,-0.0073,2612309.0,0.4760,192397.0
3,2016.0,5529742.0,0.0641,3984631.0,0.7205,566948.0
4,2015.0,5196436.0,-0.0160,1509864.0,0.2910,62605.0

In [4]:
election_results.head()

,Year,Winner,Party,Winner's Vote Count,Winner's Percent of Total Votes
0,2016,Hillary R. Clinton,Democratic,1981473,49.7
1,2012,Barack Obama,Democratic,1971820,51.1
2,2008,Barack Obama,Democratic,1959532,52.6
3,2004,Bush and Cheney,Republican,1716959,53.7
4,2000,Bush and Cheney,Republican,1437490,52.5

In [5]:
# cast year to integer in both dataframes
voting_data["Year"] = voting_data["Year"].astype(int)
election_results["Year"] = election_results["Year"].astype(int)

In [6]:
# specify outer join with how='outer'
df_merge_col = pd.merge(voting_data, election_results,  on='Year', how='outer')

In [7]:
df_merge_col.head()

,Year,Total Registered,Percentage Change from Previous Year,Total Voting,Turnout (% Voting of Total Registered),Voting Absentee (Included in Total Voting),Winner,Party,Winner's Vote Count,Winner's Percent of Total Votes
0,2019,5628035.0,-0.0100,2383646.0,0.4240,144360.0,NaN,NaN,NaN,NaN
1,2018,5666962.0,0.0331,3374382.0,0.5950,337315.0,NaN,NaN,NaN,NaN
2,2017,5489530.0,-0.0073,2612309.0,0.4760,192397.0,NaN,NaN,NaN,NaN
3,2016,5529742.0,0.0641,3984631.0,0.7205,566948.0,Hillary R. Clinton,Democratic,1981473.0,49.7
4,2015,5196436.0,-0.0160,1509864.0,0.2910,62605.0,NaN,NaN,NaN,NaN

In [8]:
# output csv
# index=False hides index column, sep="," separates at commas
df_merge_col.to_csv("complete.csv", index=False, sep=",")